language: node_js
node_js:
  - 0.8

before_script:
  - npm install -g grunt-cli
  - npm install -g testacular@canary
  - npm install -g bower
  - bower install

script:
  - grunt

notifications:
  irc: "irc.freenode.net#glimpse-dev"
